### ISSUE TITLE
Error: Invalid prefix for given prefix length.

### ISSUE THREAD

**Issue by LakshayDCoder** [walterl/proton-privoxy#60]
I using the below docker compose file
```
  proton-privoxy:
    image: walt3rl/proton-privoxy
    container_name: proton-privoxy
    environment:
      - PVPN_USERNAME=QKMxxxxxxxxxxtugmEi
      - PVPN_PASSWORD=T2XxxxxxxxxxxcTq
      - PVPN_TIER=0
      - HOST_NETWORK=192.168.1.210/24
    volumes:
      - ${CONFIGS_PATH}/protonproxy:/etc/localtime:ro
    ports:
      - 8888:8080
    restart: unless-stopped
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
```

When I start the container & check the logs I am getting the below error & I am unable to ping the container. 
```
Connecting to US-FREE#38 via UDP...

Traceback (most recent call last):

  File "/usr/bin/protonvpn", line 33, in <module>

    sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 72, in main



)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 121, in cli

    connection.fastest(protocol)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 181, in fastest

    openvpn_connect(fastest_server, protocol)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 517, in openvpn_connect

    manage_ipv6("disable")

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 677, in manage_ipv6

    ip6tables_rules = subprocess.run(["ip6tables-save"],

  File "/usr/lib/python3.10/subprocess.py", line 503, in run

    with Popen(*popenargs, **kwargs) as process:

  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save'

Error: Invalid prefix for given prefix length.

2024-10-22 18:50:21.055 778db1843b48 Info: Privoxy version 3.0.33

2024-10-22 18:50:21.055 778db1843b48 Info: Program name: privoxy

2024-10-22 18:50:21.055 778db1843b48 Info: Listening on port 8080 on IP address 0.0.0.0
```

**Comment by LakshayDCoder** [comment]
Pull request #57 should fix this issue

**Comment by walterl** [comment]
@LakshayDCoder #57 has been merged. Please check if that fixed your issue.

Please also note that I will no longer be maintaining this project: #68.
