### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by naxeras** [walterl/proton-privoxy#62]
Hi, proton has been stopped from working:

Traceback (most recent call last):

  File "/usr/bin/protonvpn", line 33, in <module>

    sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 72, in main



)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 121, in cli

    connection.fastest(protocol)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 180, in fastest

    fastest_server = get_fastest_server(server_pool)

  File "/usr/lib/python3.10/site-packages/protonvpn_cli/utils.py", line 180, in get_fastest_server

    fastest_server = random.choice(fastest_pool[:pool_size])["Name"]

  File "/usr/lib/python3.10/random.py", line 378, in choice

    return seq[self._randbelow(len(seq))]

IndexError: list index out of range

Device "proton0" does not exist.

Failed to bring up VPN :(

**Comment by 0xN1nja** [comment]
same

**Comment by biennvops** [comment]
Same issue.

**Comment by walterl** [comment]
Please note that I will no longer be maintaining this project: https://github.com/walterl/proton-privoxy/issues/68. I'll leave this issue open in case anyone else wants to have a look.
