### ISSUE TITLE
VPN Connection Fails Silently Due to Missing `ip6tables-save`

### ISSUE THREAD

**Issue by neurolag** [walterl/proton-privoxy#63]
I only just noticed that in the current image, connections to Proton VPN fail without causing the container to exit.

The following error is printed to the console:

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 121, in cli
    connection.fastest(protocol)
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 181, in fastest
    openvpn_connect(fastest_server, protocol)
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 517, in openvpn_connect
    manage_ipv6("disable")
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/connection.py", line 677, in manage_ipv6
    ip6tables_rules = subprocess.run(["ip6tables-save"],
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ip6tables-save'
```

**Comment by walterl** [comment]
#64 has been merged. Please check if that fixed your issue, and close this issue if it has.

Please also note that I will no longer be maintaining this project: https://github.com/walterl/proton-privoxy/issues/68.
